### ISSUE TITLE
new function to write in the relationships index

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-qma-elastic#1]
We need to materialize the relations between strategic indicators and factors when the assessment is stored in the ElasticSearch.

**Comment by martimanzano** [comment]
Tasks:

- [x] Create test index
- [x] Add required fields to the mapping
- [x] Add test relations
- [x] Implement qma function

Estimated effort: 15 hours.

**Comment by martimanzano** [comment]
Pending integration

Spent effort until now ~= 15 hours
